[package]
name = "year2018"
version = "0.1.0"
authors = ["Christian Persson <saser@live.se>"]
edition = "2018"

[dependencies]
base = { path = "../base" }
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"
rayon = "1.0"
nalgebra = "0.16"
typenum = "1.10"
