// +build genprotodeps

// This file copies the imports from the code generated by the `go_proto_library` targets defined by
// Gazelle. This is so that the Go module will define the appropriate dependencies in
// `go.mod`/`go.sum`, which in turn can be picked up by Gazelles `update-repos` command. As a
// result, the `go_proto_library` targets can successfully be built.

package genprotodeps

import (
	_ "context"
	_ "reflect"
	_ "sync"

	_ "github.com/golang/protobuf/proto"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/codes"
	_ "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/reflect/protoreflect"
	_ "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
)
