[package]
name = "aoc"
version = "0.1.0"
authors = ["Christian Persson <saser@live.se>"]
edition = "2018"

[dependencies]
clap = "~2.29.0"
base = { path = "../base" }
year2016 = { path = "../year2016" }
year2017 = { path = "../year2017" }
year2018 = { path = "../year2018" }
